#21 implemented a network layer
gorodskayafialka/PRORecipies pull request #36
Opened 2023-04-14 16:37 UTC by max911z

2023-04-14 22:39 UTC, aldonin requested changes

2023-04-14 22:39 UTC, aldonin commented on PRORecipies/Models/Meals.swift
> +import Foundation
Надо удалить видимо файлик

2023-04-14 22:39 UTC, aldonin commented on PRORecipies/Networking/HTTPMethod.swift
> +	case `get` = "GET"
У тебя чот с отступами, тут явно больше 2х или 4х

2023-04-14 22:39 UTC, aldonin commented on PRORecipies/Networking/HTTPMethod.swift
> +	case `get` = "GET"
И во всех файликах ниже

2023-04-14 22:39 UTC, aldonin commented on PRORecipies/Support/Constant/URLFactory.swift
> +final class URLFactory {
Нет смысла от класса, если тут все static
сделай enum

2023-04-14 22:39 UTC, aldonin commented on PRORecipies/Support/Constant/URLFactory.swift
> +
Зачем пустая строка?

2023-04-14 22:39 UTC, aldonin commented on PRORecipies/Support/Constant/URLFactory.swift
> +	static func makeGetNewsURLString() -> String {
Какие news?)

2023-04-14 22:39 UTC, aldonin commented on PRORecipies/Support/Constant/URLFactory.swift
> +		let urlString = baseURL + "\(apiKey)/"
```suggestion
		baseURL + "\(apiKey)/"
```

2023-04-14 22:39 UTC, aldonin commented on PRORecipies/Networking/Network Service/NetworkService.swift
> +struct NetworkService {
Точно не backend?))

2023-04-14 22:39 UTC, aldonin commented on PRORecipies/Networking/Network Service/NetworkService.swift
> +//  PRORecipies
Мне кажется этот файлик надо выносить из папки Networking

2023-04-15 12:58 UTC, denchicez approved these changes

2023-04-15 12:58 UTC, aldonin approved these changes

2023-04-15 13:00 UTC, merged

2023-04-15 13:19 UTC, yaanvar approved these changes