#38 add HomeViewModel
gorodskayafialka/PRORecipies pull request #57
Opened 2023-04-16 15:59 UTC by yaanvar

добавил homeViewModel

исправил проблему с большим текстом

2023-04-16 16:14 UTC, aldonin commented on PRORecipies/Views/Navigation/HomeView.swift
> +//struct HomeView_Previews: PreviewProvider {
у нас уже есть моки, давай не будем комментить

2023-04-16 17:09 UTC, max911z commented on PRORecipies/Service/NetworkService.swift
> +    var latestMeals: Remote<Void, Meals>
Насколько я понимю, эти исправления уже лежат в main, нужно подтянуть

2023-04-17 06:48 UTC, max911z commented on PRORecipies/Support/Ext+View.swift
minor: Предлагаю сделать папочку Extensions и в нее положить файлик Extension+View. Я сделал так у себя

2023-04-17 07:07 UTC, aldonin requested changes

2023-04-17 07:07 UTC, aldonin commented on PRORecipies/Support/Ext+View.swift
> +//  Ext+View.swift
давай название поменяем
Либо это будет общий файлик для всех модификаторов - тогда View+Modifiers
Либо для каждого будет свой файлик, тогда назовем по тому, что здесь происходит

2023-04-17 07:07 UTC, aldonin commented on PRORecipies/Support/Ext+View.swift
> +    @State private var appearOnce = true
название непонятное - сначала подумал, что appearOnce - это уже происзошло, но тогда с начальным значением не бьется
performed? appeared?

2023-04-17 07:07 UTC, aldonin commented on PRORecipies/Views/Navigation/HomeView.swift
> +        HomeView(homeViewModel: HomeViewModel(networkService: .makeUrlSessionedService()))
не, тут мок должен быть

2023-04-17 07:07 UTC, aldonin commented on PRORecipies/Views/Navigation/HomeView.swift
> +            MealItem(namespace: namespace, meal: meal, selectedMeal: $model.selectedMeal)
очень конечно хочется избавится от UIModel

2023-04-17 07:07 UTC, aldonin commented on PRORecipies/Views/Navigation/HomeView.swift
> +            MealItem(namespace: namespace, meal: meal, selectedMeal: $model.selectedMeal)
а тут точно в model надо писать, а не viewmodel?

2023-04-17 07:07 UTC, aldonin commented on PRORecipies/ViewModels/HomeViewModel.swift
> +    @Published var selectedMeal: String = Meal.notFoundId
кажется не используется?

2023-04-17 07:07 UTC, aldonin commented on PRORecipies/ViewModels/HomeViewModel.swift
> +    @Published var selectedFeaturedMeal: String = Meal.notFoundId
Не используется, давай удалять, оно тут не нужно

2023-04-17 08:51 UTC, max911z commented on PRORecipies/ViewModels/HomeViewModel.swift
> +    @Published var selectedMeal = Meal.notFoundId
Вроде как не используется

2023-04-17 08:56 UTC, max911z commented on PRORecipies/Views/Bars/NavigationBar.swift
> +    @EnvironmentObject var model: UIViewModel
minor: давай тогда и переменную назовем что-то типа "viewModel"

2023-04-17 08:58 UTC, yaanvar commented on PRORecipies/ViewModels/HomeViewModel.swift
> +    @Published var selectedMeal = Meal.notFoundId
используются

2023-04-17 09:27 UTC, aldonin approved these changes

2023-04-17 09:27 UTC, aldonin commented on PRORecipies/Views/MealViews/MealView.swift
> +            selectedMeal = Meal.notFoundId
selectedMeal нужен только чтобы сбросить селекшен? 
Если да, то надо на блок заменять
```
var onClose: () -> ()
```

2023-04-17 09:28 UTC, aldonin commented on PRORecipies/Support/Ext+View.swift
> +    @State private var appearOnce = true
Это не исправилось

2023-04-17 09:46 UTC, max911z approved these changes

2023-04-17 09:46 UTC, merged