#71 кнопка лайк работает нормально
gorodskayafialka/PRORecipies pull request #80
Opened 2023-04-17 19:15 UTC by denchicez

2023-04-17 19:45 UTC, yaanvar requested changes

2023-04-17 19:45 UTC, yaanvar commented on PRORecipies/ViewModels/MealViewModel.swift
> +    private let storage = FavouritesIdsStorage(storage: PersistentStorage(userDefaults: .standard))
лучше сделать инициализатор и отправить туда FavouriteIdsStorage при инициализации MealViewModel

2023-04-17 20:05 UTC, denchicez commented on PRORecipies/ViewModels/MealViewModel.swift
> +    private let storage = FavouritesIdsStorage(storage: PersistentStorage(userDefaults: .standard))
> лучше сделать инициализатор и отправить туда FavouriteIdsStorage при инициализации MealViewModel

Сейчас нормально?

2023-04-17 20:11 UTC, aldonin commented on PRORecipies/Views/MealViews/MealView.swift
> +    @Namespace var namespace
А что с неймспейсом? Надо так поменять? 
Это ничего не ломает?

2023-04-17 20:12 UTC, aldonin commented on PRORecipies/ViewModels/MealViewModel.swift
> +    @Published var meal: Meal
У нас meal вроде как не изменяется, нет смысла делать его Published

2023-04-17 20:13 UTC, aldonin commented on PRORecipies/Views/Bars/TabBar.swift
> +                    .environmentObject(uiViewModel)
??

2023-04-17 20:18 UTC, denchicez commented on PRORecipies/Views/MealViews/MealView.swift
> +    @Namespace var namespace
не ломает

2023-04-17 21:37 UTC, aldonin commented on PRORecipies/ViewModels/MealViewModel.swift
> +    @Published var showDetail = false
Зачем опять это?

2023-04-17 21:37 UTC, aldonin commented on PRORecipies/ViewModels/MealViewModel.swift
> +    init(meal: Meal, storage: FavouritesIdsStorage = FavouritesIdsStorage(storage: PersistentStorage(userDefaults: .standard))) {
```suggestion
    init(
    meal: Meal, 
    storage: FavouritesIdsStorage = .init(storage: PersistentStorage(userDefaults: .standard))) {
```

2023-04-18 06:46 UTC, max911z approved these changes

2023-04-18 07:18 UTC, aldonin commented on PRORecipies/ViewModels/MealViewModel.swift
> +    private var storage = FavouritesIdsStorage(storage: PersistentStorage(userDefaults: .standard))
Ты его в конструкторе задаешь, зачем тут еще раз создавать?

2023-04-18 07:22 UTC, yaanvar approved these changes

2023-04-18 07:22 UTC, merged